const config = {
  verbose: true,
  jest: {
    setupFilesAfterEnv: ["src/setupTests.js"],
  },
};

module.exports = config;

// this file was generated by running `npx @storybook/cli@latest sb init --type react_scripts`
// if you have any problems, please open an issue here:
